name: Auto. update version

on:
  schedule:
    - cron: '0 4 * * *' # Check daily at 4am UTC
  workflow_dispatch: # Allow manual trigger

jobs:
  update-aur:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    container: 
      image: archlinux:base-devel

    steps:
      - name: Install Dependencies
        run: |
          pacman -Syu --noconfirm git python

      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          persist-credentials: true

      - name: Check and Update PKGBUILD
        id: check
        run: |
          python -u .github/workflows/scripts/update_ver.py

      - name: Generate .SRCINFO
        if: steps.check.outputs.updated == 'true'
        run: |
          # Install build dependencies as root
          source PKGBUILD
          pacman -S --noconfirm --needed ${depends[@]} ${makedepends[@]}

          # `makepkg` cannot run as root. Create builder and own the workspace to it
          useradd builder -m || true
          chown -R builder:builder "$GITHUB_WORKSPACE"

          # Update .SRCINFO
          su builder -c "cd $GITHUB_WORKSPACE && makepkg --printsrcinfo > .SRCINFO"

          # Build package
          su builder -c "cd $GITHUB_WORKSPACE && makepkg --noconfirm"

          # Restore ownership
          chown -R $USER:$USER "$GITHUB_WORKSPACE"

      - name: Prepare for Commit
        if: steps.check.outputs.updated == 'true'
        run: |
          # Mark the repository as safe for git operations
          git config --system --add safe.directory $GITHUB_WORKSPACE

      - uses: stefanzweifel/git-auto-commit-action@v7
        if: steps.check.outputs.updated == 'true'
        with:
          commit_message: "Update to ${{ steps.check.outputs.version }}"
          tag_name: "v${{ steps.check.outputs.version }}"
          file_pattern: "PKGBUILD .SRCINFO"
